#!/usr/bin/env python3
"""Bake theme/icons/g_IconLoading.png (32x32) -> src/SMS_LoadingRGBA.c.
The loading spinner (SMS_PgInd.c) uploads this as a GS texture and rotates it,
so it must be UNCOMPRESSED (the spinner thread must not run an lzma2 decode) and
NOT folded into the XZ-packed slot-ordered icon blob. Same byte format as
bake_icons_rgba.py: R,G,B,A; alpha 0..255 -> 0..0x80 (0x80==opaque); A==0 -> RGB zeroed."""
import os
from PIL import Image
SRC = os.environ.get("LOADING_PNG", "/work/theme/icons/g_IconLoading.png")
OUT = os.environ.get("LOADING_OUT", "/work/src/SMS_LoadingRGBA.c")
im = Image.open(SRC).convert("RGBA"); w, h = im.size
assert (w, h) == (32, 32), "g_IconLoading.png must be 32x32, got %r" % ((w, h),)
px = im.tobytes(); out = bytearray(w * h * 4)
for i in range(w * h):
    r, g, b, a = px[i*4], px[i*4+1], px[i*4+2], px[i*4+3]
    a2 = int(round(a * 128.0 / 255.0))
    if a2 <= 0: r = g = b = 0; a2 = 0
    if a2 >= 0x80: a2 = 0x80
    out[i*4:i*4+4] = bytes((r, g, b, a2))
lines = ["\t" + ",".join("0x%02x" % v for v in out[o:o+16]) + "," for o in range(0, len(out), 16)]
with open(OUT, "w", newline="\n") as f:
    f.write("/* AUTO-GENERATED by tools/bake_loading_rgba.py from theme/icons/g_IconLoading.png (32x32).\n"
            " * RGBA, alpha 0..0x80 (0x80==opaque), transparent pixels RGB-zeroed. Uncompressed:\n"
            " * the loading spinner uploads it as a GS texture and must not lzma2-decode. */\n\n"
            "const unsigned char g_IconLoadingRGBA[ 4096 ] "
            "__attribute__(   (  aligned( 16 ), section( \".data\" )  )   ) = {\n"
            + "\n".join(lines) + "\n};\n")
print("wrote", OUT, "(%d bytes RGBA)" % len(out))
