#!/usr/bin/env python3
"""Bake theme/icons/*.png -> SMS-v1/src/SMS_IconsRGBA.c (build-time).

This makes PNG the source of truth for SMS's GUI icons, replacing the legacy
"MPEG-Intra"/IPU blobs. Each PNG is converted to the EXACT byte format the PS2
IPU used to produce (so the GS draw path is unchanged):

  * byte order  R, G, B, A  (GS PSMCT32; one 32-bit word per pixel)
  * alpha scaled 0..255 (PNG) -> 0..0x80 (PS2: 0x80 == fully opaque), so smooth
    8-bit PNG alpha survives as ~128 levels (vs the old lossy 3-level dark key)
  * fully transparent pixels (A==0) have RGB zeroed, matching the IPU's SETTH
    behaviour (keeps edges clean if the draw path ever ignores alpha)

The slot order MUST match GUI_LoadIcons() in SMS_GUIcons.c. g_IconBall keeps its
IPU blob (the player ball uses IPU_LoadImage); here it only fills its GUI slot.
"""
import os, sys
from PIL import Image

ICON_DIR = os.environ.get("ICON_DIR", "/work/theme/icons")
OUT      = os.environ.get("RGBA_OUT", "/work/SMS-v1/src/SMS_IconsRGBA.c")

# Slot order — copied verbatim from SMS_GUIcons.c (s_pBrowserIcons / s_pMiscIcons
# / s_pBrowserDevIcons). Browser+Misc are 32x32, Dev is 48x48.
BROWSER = ["s_IconFolder","s_IconAVI","s_IconMP3","s_IconM3U","s_IconFile",
           "s_IconPart","s_IconAVIS","s_IconShare","s_IconPicture"]
MISC    = ["s_IconError","s_IconDisplay","s_IconHelp","s_IconNetwork",
           "s_IconBrowser","s_IconPlayer","s_IconOn","s_IconOff","s_IconSave",
           "s_IconExit","s_IconFinish","g_IconBall"]
DEV     = ["s_IconUSB","s_IconCDROM","s_IconHDD","s_IconCDDA","s_IconHost",
           "s_IconDVD","s_IconSMB","s_IconMX4SIO","s_IconATA","s_IconILINK","s_IconMMCE",
           "s_IconDVDVID","s_IconCDVDERROR"]
# device icon slots: 0..6 base, 7=MX4SIO, 8=ATA, 9=iLink, 10=MMCE, 11=DVDVID (DVD-Video),
# 12=CDVDERROR (disc error / failed CDDA). Must match _dev_icon_index() in SMS_GUIDevMenu.c
# and the s_BrowserDeviceIcons[13] array + GUI_LoadIcons dev loop (i < 13) in SMS_GUIcons.c.
# ATA + iLink are BDM mass: devices (icon chosen via g_AtaMask / g_IlinkMask on a
# m_DevID==0 unit); MMCE is the separate mmce0: device (its own m_DevID -> slot 10).
# Disc sub-type icons (1/3/5 -> CDROM/CDDA/DVD/DVDVID/CDVDERROR) are chosen in _dev_icon_index
# from g_pCDDACtx (audio vs data CD) and g_CurDiscDVDV (DVD-Video vs data DVD).

def bake(name, expect_wh):
    p = os.path.join(ICON_DIR, name + ".png")
    im = Image.open(p).convert("RGBA")
    w, h = im.size
    if (w, h) != expect_wh:
        sys.exit("ERROR: %s is %dx%d, expected %dx%d" % (name, w, h, *expect_wh))
    px = im.tobytes()                       # RGBA, row-major, top-left first
    out = bytearray(w * h * 4)
    op = 0
    for i in range(w * h):
        r, g, b, a = px[i*4], px[i*4+1], px[i*4+2], px[i*4+3]
        a2 = int(round(a * 128.0 / 255.0))  # 0..255 -> 0..0x80
        if a2 <= 0:
            r = g = b = 0                   # zero fully-transparent pixels
            a2 = 0
        if a2 >= 0x80:
            a2 = 0x80; op += 1
        out[i*4+0] = r; out[i*4+1] = g; out[i*4+2] = b; out[i*4+3] = a2
    return w, h, bytes(out), op

def c_blob(symbol, blob):
    lines = []
    for off in range(0, len(blob), 16):
        chunk = blob[off:off+16]
        lines.append("\t" + ",".join("0x%02x" % v for v in chunk) + ",")
    # section(".data") keeps this large array OUT of the GP-relative small-data
    # area (.sdata) so it doesn't overflow the +/-32KB GPREL16 window at link time.
    return ("const unsigned char %s[ %d ] "
            "__attribute__(   (  aligned( 16 ), section( \".data\" )  )   ) = {\n%s\n};\n"
            % (symbol, len(blob), "\n".join(lines)))

def main():
    import lzma
    # Bake every slot IN ORDER and concatenate the raw RGBA: 9 browser (32x32),
    # 12 misc (32x32), 11 dev (48x48). GUI_LoadIcons() decompresses the blob and
    # indexes it by fixed offset -- so this order MUST match the loops there.
    raw = bytearray()
    print("%-15s %5s %6s" % ("icon", "dims", "opaq%"))
    for names, wh in ((BROWSER, (32, 32)), (MISC, (32, 32)), (DEV, (48, 48))):
        for n in names:
            w, h, blob, op = bake(n, wh)
            raw += blob
            print("%-15s %2dx%-2d %5.1f%%" % (n, w, h, 100.0 * op / (w * h)))

    # XZ / LZMA2 with a CRC32 check -- exactly what SMS's embedded decoder accepts
    # (lzma2.c + xz_dec_*, XZ_SINGLE mode; xz_crc64 is NOT linked; no BCJ filter).
    comp = lzma.compress(
        bytes(raw), format=lzma.FORMAT_XZ, check=lzma.CHECK_CRC32,
        filters=[{"id": lzma.FILTER_LZMA2, "preset": 9, "dict_size": 1 << 20}],
    )

    parts = [
        "/* AUTO-GENERATED by tools/bake_icons_rgba.py from theme/icons/*.png.\n"
        " * DO NOT EDIT BY HAND -- edit the PNGs and re-run the bake tool:\n"
        " *   docker run --rm -v <repo>:/work sms-ipu-tools python3 /work/tools/bake_icons_rgba.py\n"
        " * All icon RGBA (R,G,B,A; alpha 0..0x80, transparent zeroed) concatenated in\n"
        " * slot order [ 9 browser 32x32 | 12 misc 32x32 | 11 dev 48x48 ], XZ-compressed.\n"
        " * GUI_LoadIcons() decompresses g_RGBA_Blob (g_RGBA_RawSize bytes) and slices it. */\n\n",
        c_blob("g_RGBA_Blob", comp),
        "\nconst unsigned int g_RGBA_BlobSize = %d;\n" % len(comp),
        "const unsigned int g_RGBA_RawSize  = %d;\n" % len(raw),
    ]
    with open(OUT, "w", newline="\n") as f:
        f.write("".join(parts))
    print("\nwrote %s : icons %d raw -> %d xz (-%d%%), %d browser / %d misc / %d dev slots"
          % (OUT, len(raw), len(comp), 100 * (len(raw) - len(comp)) // len(raw),
             len(BROWSER), len(MISC), len(DEV)))

if __name__ == "__main__":
    main()
