#!/usr/bin/env python3
"""Bake theme/icons/*.png -> SMS-v1/src/SMS_IconsRGBA.c (build-time).

This makes PNG the source of truth for SMS's GUI icons, replacing the legacy
"MPEG-Intra"/IPU blobs. Each PNG is converted to the EXACT byte format the PS2
IPU used to produce (so the GS draw path is unchanged):

  * byte order  R, G, B, A  (GS PSMCT32; one 32-bit word per pixel)
  * alpha scaled 0..255 (PNG) -> 0..0x80 (PS2: 0x80 == fully opaque), so smooth
    8-bit PNG alpha survives as ~128 levels (vs the old lossy 3-level dark key)
  * fully transparent pixels (A==0) have RGB zeroed, matching the IPU's SETTH
    behaviour (keeps edges clean if the draw path ever ignores alpha)

The slot order MUST match GUI_LoadIcons() in SMS_GUIcons.c. g_IconBall keeps its
IPU blob (the player ball uses IPU_LoadImage); here it only fills its GUI slot.
"""
import os, sys
from PIL import Image

ICON_DIR = os.environ.get("ICON_DIR", "/work/theme/icons")
OUT      = os.environ.get("RGBA_OUT", "/work/SMS-v1/src/SMS_IconsRGBA.c")

# Slot order — copied verbatim from SMS_GUIcons.c (s_pBrowserIcons / s_pMiscIcons
# / s_pBrowserDevIcons). Browser+Misc are 32x32, Dev is 48x48.
BROWSER = ["s_IconFolder","s_IconAVI","s_IconMP3","s_IconM3U","s_IconFile",
           "s_IconPart","s_IconAVIS","s_IconShare","s_IconPicture"]
MISC    = ["s_IconError","s_IconDisplay","s_IconHelp","s_IconNetwork",
           "s_IconBrowser","s_IconPlayer","s_IconOn","s_IconOff","s_IconSave",
           "s_IconExit","s_IconFinish","g_IconBall"]
DEV     = ["s_IconUSB","s_IconCDROM","s_IconHDD","s_IconCDDA","s_IconHost",
           "s_IconDVD","s_IconSMB","s_IconMX4SIO"]  # slot 7 = MX4SIO (was CDDA dup)

# Pending device icons: art delivered by the graphics team but the device backend
# is NOT implemented in SMS yet, so they are intentionally NOT baked (a slot with
# no _dev_icon_index() mapping would be dead data). PNGs live in the icon dir:
#   s_IconATA   - internal HDD via BDM (exFAT/FAT, cf. OPL ata_bd), distinct from PFS hdd0:
#   s_IconMMCE  - Memory Card Emulator (SD2PSX / MemCard PRO)
#   s_IconILINK - i.LINK / IEEE1394 storage
# To wire one up when its backend lands: append the name to DEV above, bump the
# array sizes + dev loop bound in SMS_GUIcons.c (g_RGBA_Dev / s_BrowserDeviceIcons /
# s_SizeBrowserDevIcons / GUI_LoadIcons), and add a _dev_icon_index() case in
# SMS_GUIDevMenu.c that returns the new slot for that device.

def bake(name, expect_wh):
    p = os.path.join(ICON_DIR, name + ".png")
    im = Image.open(p).convert("RGBA")
    w, h = im.size
    if (w, h) != expect_wh:
        sys.exit("ERROR: %s is %dx%d, expected %dx%d" % (name, w, h, *expect_wh))
    px = im.tobytes()                       # RGBA, row-major, top-left first
    out = bytearray(w * h * 4)
    op = 0
    for i in range(w * h):
        r, g, b, a = px[i*4], px[i*4+1], px[i*4+2], px[i*4+3]
        a2 = int(round(a * 128.0 / 255.0))  # 0..255 -> 0..0x80
        if a2 <= 0:
            r = g = b = 0                   # zero fully-transparent pixels
            a2 = 0
        if a2 >= 0x80:
            a2 = 0x80; op += 1
        out[i*4+0] = r; out[i*4+1] = g; out[i*4+2] = b; out[i*4+3] = a2
    return w, h, bytes(out), op

def c_array(symbol, blob):
    lines = []
    for off in range(0, len(blob), 16):
        chunk = blob[off:off+16]
        lines.append("\t" + ",".join("0x%02x" % v for v in chunk) + ",")
    # section(".data") keeps these large arrays OUT of the GP-relative small-data
    # area (.sdata) -- otherwise they overflow the +/-32KB GPREL16 window at link
    # time. This matches the convention SMS uses for its other big blobs.
    return ("static const unsigned char %s[ %d ] "
            "__attribute__(   (  aligned( 16 ), section( \".data\" )  )   ) = {\n%s\n};\n"
            % (symbol, len(blob), "\n".join(lines)))

def main():
    uniq = []
    seen = set()
    for n in BROWSER + MISC + DEV:
        if n not in seen:
            seen.add(n); uniq.append(n)

    sym = {n: "rgba_" + n for n in uniq}
    parts = [
        "/* AUTO-GENERATED by tools/bake_icons_rgba.py from theme/icons/*.png.\n"
        " * DO NOT EDIT BY HAND -- edit the PNGs and re-run the bake tool:\n"
        " *   docker run --rm -v <repo>:/work sms-ipu-tools python3 /work/tools/bake_icons_rgba.py\n"
        " * Format: R,G,B,A bytes (GS PSMCT32), alpha 0..0x80, transparent zeroed. */\n\n"
    ]
    print("%-15s %5s %6s" % ("icon", "dims", "opaq%"))
    for n in uniq:
        wh = (48, 48) if n in DEV else (32, 32)
        w, h, blob, op = bake(n, wh)
        parts.append(c_array(sym[n], blob))
        print("%-15s %2dx%-2d %5.1f%%" % (n, w, h, 100.0 * op / (w*h)))

    def ptr_arr(cname, names):
        # The pointer arrays are tiny (<=48 bytes) and stay in small-data so the
        # GPREL16 references generated in SMS_GUIcons.c resolve; only the large
        # pixel arrays above need forcing to .data.
        body = ",\n ".join(sym[n] for n in names)
        return ("const unsigned char* const %s[ %d ] = {\n %s\n};\n"
                % (cname, len(names), body))

    parts.append("\n" + ptr_arr("g_RGBA_Browser", BROWSER))
    parts.append("\n" + ptr_arr("g_RGBA_Misc",    MISC))
    parts.append("\n" + ptr_arr("g_RGBA_Dev",     DEV))

    with open(OUT, "w", newline="\n") as f:
        f.write("".join(parts))
    print("\nwrote %s (%d unique icons, %d browser / %d misc / %d dev slots)"
          % (OUT, len(uniq), len(BROWSER), len(MISC), len(DEV)))

if __name__ == "__main__":
    main()
