#!/usr/bin/env bash
# gen-test-media.sh -- build SMS-test-media.zip from scratch with ffmpeg.
# Every clip is synthetic (testsrc2 + sine), so nothing copyrighted ever
# enters the repo or the release. Run by .github/workflows/test-media.yml
# on every push to master; can also be run locally (needs ffmpeg + zip).
set -euo pipefail

OUT=SMS-test-media
ZIP=SMS-test-media.zip

FF="ffmpeg -hide_banner -loglevel error -y"
TONE20="sine=frequency=440:duration=20"          # audio matrix clips
VID15="testsrc2=size=640x480:rate=30:duration=15"  # video matrix clips
TONE15="sine=frequency=440:duration=15"
# mp4-suite: 30 s pattern + 1 kHz tone, matching the documented test plan
VID30="testsrc2=size=640x480:rate=30:duration=30"
VID30S="testsrc2=size=320x240:rate=30:duration=30"
TONE30="sine=frequency=1000:duration=30:sample_rate=48000"

rm -rf "$OUT" "$ZIP"
mkdir -p "$OUT/audio" "$OUT/video" "$OUT/mp4-suite"

# --- audio matrix: one clip per audio decoder SMS ships ---------------------
$FF -f lavfi -i "$TONE20" -c:a libmp3lame -b:a 192k "$OUT/audio/01_mp3_20s.mp3"
$FF -f lavfi -i "$TONE20" -c:a libvorbis -q:a 5   "$OUT/audio/02_ogg_20s.ogg"
$FF -f lavfi -i "$TONE20" -c:a wmav2 -b:a 128k    "$OUT/audio/03_wma_20s.wma"
$FF -f lavfi -i "$TONE20" -c:a flac               "$OUT/audio/04_flac_20s.flac"
$FF -f lavfi -i "$TONE20" -c:a ac3 -b:a 192k      "$OUT/audio/05_ac3_20s.ac3"
$FF -f lavfi -i "$TONE20" -c:a aac -b:a 128k      "$OUT/audio/06_m4a_20s.m4a"
$FF -f lavfi -i "$TONE20" -c:a aac -b:a 128k -f adts "$OUT/audio/07_aac_adts_20s.aac"
$FF -f lavfi -i "$TONE20" -c:a mp2 -b:a 192k      "$OUT/audio/08_mp2_20s.mp2"
printf '%s\n' "01_mp3_20s.mp3" "02_ogg_20s.ogg" "04_flac_20s.flac" > "$OUT/audio/00_playlist.m3u"

# --- video matrix: AVI/XviD, MPEG-1/2 PS (IPU path), JPEG -------------------
$FF -f lavfi -i "$VID15" -f lavfi -i "$TONE15" \
    -c:v mpeg4 -vtag XVID -b:v 1500k -bf 0 -g 30 -c:a libmp3lame -b:a 128k \
    "$OUT/video/01_avi_xvid_mp3.avi"
cp "$OUT/video/01_avi_xvid_mp3.avi" "$OUT/video/02_same_as_avi.divx"
cp "$OUT/video/01_avi_xvid_mp3.avi" "$OUT/video/03_same_as_avi.xvid"
$FF -f lavfi -i "$VID15" -f lavfi -i "$TONE15" \
    -c:v mpeg2video -b:v 2500k -g 15 -c:a mp2 -b:a 192k -f vob \
    "$OUT/video/04_mpg_mpeg2_mp2.mpg"
$FF -f lavfi -i "$VID15" -f lavfi -i "$TONE15" \
    -c:v mpeg1video -b:v 1150k -g 15 -c:a mp2 -b:a 192k -f vob \
    "$OUT/video/05_mpg_mpeg1_mp2.mpg"
$FF -f lavfi -i "$VID15" -frames:v 1 -q:v 3 "$OUT/video/06_still_image.jpg"

# --- mp4-suite: the MOV/MP4 verification set --------------------------------
# Encoder settings mirror the documented plan: MPEG-4 Part 2 (mp4v), no
# B-frames, keyframe every 30, AAC 128k stereo 48 kHz.
$FF -f lavfi -i "$VID30" -f lavfi -i "$TONE30" \
    -c:v mpeg4 -vtag mp4v -b:v 1500k -bf 0 -g 30 -c:a aac -b:a 128k -ac 2 \
    -movflags +faststart "$OUT/mp4-suite/01-TARGET-mp4v-640x480-aac.mp4"
$FF -f lavfi -i "$VID30S" -f lavfi -i "$TONE30" \
    -c:v mpeg4 -vtag mp4v -b:v 600k -bf 0 -g 30 -c:a aac -b:a 128k -ac 2 \
    -movflags +faststart "$OUT/mp4-suite/02-small-mp4v-320x240-aac.mp4"
$FF -f lavfi -i "$VID30" -f lavfi -i "$TONE30" \
    -c:v mpeg4 -vtag XVID -b:v 1500k -bf 0 -g 30 -c:a libmp3lame -b:a 128k \
    "$OUT/mp4-suite/03-CONTROL-same-video-in.avi"
$FF -f lavfi -i "sine=frequency=1000:duration=20:sample_rate=48000" \
    -c:a aac -b:a 128k -ac 2 -movflags +faststart \
    "$OUT/mp4-suite/04-audioonly-aac.mp4"
$FF -f lavfi -i "$VID30" -f lavfi -i "$TONE30" \
    -c:v libx264 -b:v 1500k -c:a aac -b:a 128k -ac 2 -movflags +faststart \
    "$OUT/mp4-suite/05-NEGATIVE-h264-should-fail.mp4"
# #6: identical to #1 but WITHOUT faststart -> moov lands after mdat.
$FF -f lavfi -i "$VID30" -f lavfi -i "$TONE30" \
    -c:v mpeg4 -vtag mp4v -b:v 1500k -bf 0 -g 30 -c:a aac -b:a 128k -ac 2 \
    "$OUT/mp4-suite/06-ROBUST-moov-at-end.mp4"

# --- READMEs -----------------------------------------------------------------
cat > "$OUT/README-TEST-MATRIX.md" <<'MDEOF'
# SMS Test Media Pack

One short clip per format SMS supports, for verifying a build on hardware.
Copy the whole folder to a USB stick (or any device SMS browses) and play
each file. Everything is synthetically generated (ffmpeg testsrc2 + sine
tone), so there is no copyrighted material and files are small.

Auto-regenerated by CI on every push to master
(.github/workflows/test-media.yml -> tools/gen-test-media.sh).

## audio/ -- audio decoders (20 s, 440 Hz tone)

| File             | Verifies                                            |
|------------------|-----------------------------------------------------|
| 00_playlist.m3u  | Playlist parsing + continuous playback (mp3->ogg->flac auto-advance) |
| 01_mp3_20s.mp3   | MP3 decode (baseline audio path)                    |
| 02_ogg_20s.ogg   | Vorbis decode                                       |
| 03_wma_20s.wma   | WMA decode                                          |
| 04_flac_20s.flac | FLAC decode                                         |
| 05_ac3_20s.ac3   | AC3 decode                                          |
| 06_m4a_20s.m4a   | AAC in ISO-BMFF via the M4A audio-only reader       |
| 07_aac_adts_20s.aac | Raw ADTS AAC                                     |
| 08_mp2_20s.mp2   | MPEG audio layer 2                                  |

## video/ -- video pipelines (15 s, test pattern + tone)

| File                    | Verifies                                          |
|-------------------------|---------------------------------------------------|
| 01_avi_xvid_mp3.avi     | MPEG-4 ASP (XviD) + MP3 in AVI -- the classic path |
| 02_same_as_avi.divx     | .divx extension routing (same file)               |
| 03_same_as_avi.xvid     | .xvid extension routing (same file)               |
| 04_mpg_mpeg2_mp2.mpg    | MPEG-2 in MPEG-PS -- IPU hardware decoder         |
| 05_mpg_mpeg1_mp2.mpg    | MPEG-1 in MPEG-PS -- IPU hardware decoder         |
| 06_still_image.jpg      | JPEG image viewer                                 |

For video files also check: FF/REW/scrollbar seeking, pause/resume,
and that the clock corner is not corrupted after returning to the browser.

## mp4-suite/ -- MP4 verification set (see its README-TEST-PLAN.md)

The targeted suite for the MOV/MP4 demuxer work: mp4v+AAC playback,
esds-seeded VOL headers, seeking, audio-only fall-through, H.264
rejection, moov-at-end robustness.

## Expected failures (things that SHOULD error cleanly, not hang/crash)

- mp4-suite/05-NEGATIVE-h264-should-fail.mp4 -- H.264 is not supported on PS2.
- Any H.265/VP9/AV1 file -- re-encode to MPEG-4 Part 2 (XviD) instead.
MDEOF

cat > "$OUT/mp4-suite/README-TEST-PLAN.md" <<'MDEOF'
# SMS MP4 test set

Copy the whole folder to a USB stick / MX4SIO card and open each file in SMS.
All clips are a 30-second colour test pattern with motion plus a steady 1 kHz
tone, so audio/video sync problems are obvious.

**Test them in order.** Each one narrows down where a failure is, so a later
file's result is only meaningful once the earlier ones are known.

| # | File | What it proves | Expected |
|---|------|----------------|----------|
| 1 | `01-TARGET-mp4v-640x480-aac.mp4` | **The headline case.** MPEG-4 Part 2 + AAC, 640x480, 30 fps | Video plays with sound |
| 2 | `02-small-mp4v-320x240-aac.mp4` | Separates *correctness* from *speed* | Video plays; smoother than #1 |
| 3 | `03-CONTROL-same-video-in.avi` | **Control.** Same video, AVI -- the path that already worked | Plays (unchanged behaviour) |
| 4 | `04-audioonly-aac.mp4` | Audio-only `.mp4` still falls back to the audio reader | Plays as music, visualiser screen |
| 5 | `05-NEGATIVE-h264-should-fail.mp4` | **Meant to fail.** H.264, unsupported | Clean error -- *no hang, no crash* |
| 6 | `06-ROBUST-moov-at-end.mp4` | `moov` after `mdat`; exercises the `File_Skip` EOF fix | Plays, but may be slow to open |

## Reading the results

- **#1 works** -> MP4 video support is real. Ship it.
- **#1 fails but #3 (AVI) plays** -> the decoder is fine; the fault is in the
  container routing or the esds VOL seeding, not in MPEG-4 decoding.
- **#1 and #3 both fail** -> the problem is the MPEG-4 Part 2 decoder or raw
  speed, and predates any of the MP4 work.
- **#1 stutters but #2 is smooth** -> correctness is fine, 640x480 is simply
  too much for the EE at this bitrate. Try a lower bitrate before concluding.
- **#5 hangs or crashes instead of erroring** -> a real bug worth fixing.
- **#6 hangs** -> the `File_Skip` EOF fix did not hold. (Slow is expected --
  `moov` sits after the data, so SMS must read past ~6 MB first.)

## Also worth checking on #1

- **Playback speed / sync.** The frame rate is derived from `mdhd` timescale /
  `stts` delta = exactly 30 fps. Wrong speed or drift means that derivation
  is wrong.
- **FF / REW / the scrollbar should WORK** (MOV Seek callback, commit 6b1ae7b).
  Seek lands on a keyframe (every 30 frames here) and resumes. If seeking is
  dead or crashes, that commit is at fault.
- **Continuous playback must NOT chain these videos.** `.mp4` is classified as
  video precisely so finishing one does not auto-play the next.

## Encoder settings used

MPEG-4 Part 2 (`mp4v`), no B-frames, keyframe every 30 frames, 1500 kbit/s
video (600k for #2), AAC 128 kbit/s stereo 48 kHz. To make more from your own
footage:

```bash
ffmpeg -i INPUT.mp4 -c:v mpeg4 -vtag mp4v -b:v 1500k -bf 0 -g 30 -s 640x480 -c:a aac -b:a 128k -ac 2 -movflags +faststart OUTPUT.mp4
```

That is also the exact command to give anyone asking how to get their videos
onto SMS.
MDEOF

zip -9 -r -q "$ZIP" "$OUT"
ls -la "$ZIP"
