name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    # ps2dev/ps2dev:v1.0 is the toolchain this project targets.
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip

    - uses: actions/checkout@v4
    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow || true

    - name: Compile project
      run: |
        make all --trace

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "$GITHUB_OUTPUT"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: SMS-${{ steps.slug.outputs.sha8 }}
        path: bin/SMS.elf
